# Generated by Django 3.2.5 on 2022-05-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myToDo3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myToDo',
            new_name='myToDo3',
        ),
    ]
